version: 2

project_name: spooliq

before:
  hooks:
    - go mod tidy
    - go generate ./...

# Build otimizado para Linux/Docker
builds:
  - id: spooliq
    main: ./main.go
    binary: spooliq
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
      - -a
    ldflags:
      - -s -w
      - -extldflags "-static"
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

# Compressão UPX
upx:
  - enabled: true
    compress: best
    lzma: true
    goos: [linux]

# Docker Images
dockers_v2:
  - images:
      - "{{ .Env.ECR_REGISTRY }}/{{ .Env.REPOSITORY_OWNER }}/{{ .ProjectName }}"
    tags:
      - "{{ .Version }}"
      - "latest"
    build:
      dockerfile: dockerfile.with-ca
      platform: "linux/amd64"
      pull: true
      build_args:
        GITHUB_TOKEN: "{{ .Env.GITHUB_TOKEN }}"
        VERSION: "{{.Version}}"
      extra_files:
        - go.mod
        - go.sum
        - main.go
        - app/
        - core/
        - features/
        - routes/
        - docs/
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "https://github.com/RodolfoBonis/spooliq"

# Archives
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    ids:
      - spooliq

# Changelog
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "Increment version"
      - "Merge pull request"
  groups:
    - title: '🚀 Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: '🐛 Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: '♻️ Refactoring'
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 300

# GitHub Release
release:
  github:
    owner: RodolfoBonis
    name: spooliq
  prerelease: auto
  name_template: "v{{.Version}}"
  header: |
    ## SpoolIQ v{{.Version}}
    
    **Released:** {{ .Date }}
    
  footer: |
    ---
    ### 🐳 Docker Image
    ```bash
    docker pull {{ .Env.ECR_REGISTRY }}/{{ .Env.REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Version }}
    ```
    
    ### 📊 Deployment
    - **K3s Cluster:** Automatically deployed via ArgoCD
    - **Monitoring:** Available in SigNoz
    
    **Full Changelog:** [{{ .PreviousTag }}...{{ .Tag }}](https://github.com/RodolfoBonis/spooliq/compare/{{ .PreviousTag }}...{{ .Tag }})

# Snapshot para desenvolvimento
snapshot:
  version_template: "{{ incpatch .Version }}-dev"

# Checksum
checksum:
  name_template: 'checksums.txt'