; HEADER_BLOCK_START
; generated by OrcaSlicer 1.9.0 on 2024-05-01 10:00:00
; HEADER_BLOCK_END
M73 P0 R65
G90
G21
M83
G1 Z0.2 F720
G1 X90 Y90 E2 F1200
G1 X110 Y110 E4
; CONFIG_BLOCK_START
; model printing time: 58m 20s; total estimated time: 1h 5m 30s
; total filament weight [g] : 12.34,5.60
; filament used [mm] = 4100.00,1800.00
; filament_colour = #00FF00;#FF0000
; filament_type = PLA;PETG
; CONFIG_BLOCK_END
