; generated by PrusaSlicer 2.7.1+linux on 2024-05-01 at 12:00:00 UTC
;
M73 P0 R90
M201 X1000 Y1000 Z200 E5000
G90
G21
M83
G1 Z0.2 F720
G1 X90 Y90 E2 F1200
G1 X110 Y110 E4
G1 X90 Y110 E6
M104 S0
M140 S0
; filament used [mm] = 3300.50, 1200.25
; filament used [cm3] = 7.94, 2.89
; filament used [g] = 9.85, 3.58
; total filament used [g] = 13.43
; estimated printing time (normal mode) = 1h 23m 45s
; filament_colour = #FF8800;#1188FF
; filament_type = PLA;PETG
; prusaslicer_config = begin
; nozzle_diameter = 0.4,0.4
; filament_diameter = 1.75,1.75
; prusaslicer_config = end
