package parser

import (
	"bytes"
	"os"
	"strings"
	"testing"

	"github.com/RodolfoBonis/spooliq/features/slicer/domain/entities"
)

func analyzeFixture(t *testing.T, name string) *entities.Analysis {
	t.Helper()
	f, err := os.Open("testdata/" + name)
	if err != nil {
		t.Fatalf("open fixture: %v", err)
	}
	t.Cleanup(func() { _ = f.Close() })
	info, err := f.Stat()
	if err != nil {
		t.Fatalf("stat fixture: %v", err)
	}
	a, err := ParseGCode(f, info.Size())
	if err != nil {
		t.Fatalf("ParseGCode: %v", err)
	}
	return a
}

func TestParseGCode_PrusaSlicer(t *testing.T) {
	a := analyzeFixture(t, "prusaslicer.gcode")

	if a.Source != entities.SourceGCode {
		t.Errorf("source = %q", a.Source)
	}
	if a.Slicer.Name != "PrusaSlicer" {
		t.Errorf("slicer name = %q", a.Slicer.Name)
	}
	if !strings.HasPrefix(a.Slicer.Version, "2.7.1") {
		t.Errorf("slicer version = %q", a.Slicer.Version)
	}
	if len(a.Plates) != 1 {
		t.Fatalf("plates = %d", len(a.Plates))
	}
	p := a.Plates[0]
	if p.PrintTimeSeconds != 1*3600+23*60+45 {
		t.Errorf("print time = %d", p.PrintTimeSeconds)
	}
	if p.Estimated {
		t.Errorf("expected estimated=false")
	}
	if len(p.Filaments) != 2 {
		t.Fatalf("filaments = %d", len(p.Filaments))
	}
	if p.Filaments[0].Grams != 9.85 || p.Filaments[0].ColorHex != "#FF8800" || p.Filaments[0].Material != "PLA" {
		t.Errorf("slot1 = %+v", p.Filaments[0])
	}
	if p.Filaments[0].LengthMM == nil || *p.Filaments[0].LengthMM != 3300.5 {
		t.Errorf("slot1 length = %v", p.Filaments[0].LengthMM)
	}
	if p.Filaments[1].Grams != 3.58 || p.Filaments[1].ColorHex != "#1188FF" || p.Filaments[1].Material != "PETG" {
		t.Errorf("slot2 = %+v", p.Filaments[1])
	}
}

func TestParseGCode_OrcaSlicer(t *testing.T) {
	a := analyzeFixture(t, "orcaslicer.gcode")

	if a.Slicer.Name != "OrcaSlicer" {
		t.Errorf("slicer name = %q", a.Slicer.Name)
	}
	p := a.Plates[0]
	// Prefer the TOTAL estimated time (includes prep), not model printing time.
	if p.PrintTimeSeconds != 1*3600+5*60+30 {
		t.Errorf("print time = %d, want total estimated", p.PrintTimeSeconds)
	}
	if len(p.Filaments) != 2 {
		t.Fatalf("filaments = %d", len(p.Filaments))
	}
	if p.Filaments[0].Grams != 12.34 || p.Filaments[0].ColorHex != "#00FF00" {
		t.Errorf("slot1 = %+v", p.Filaments[0])
	}
	if p.Filaments[1].Grams != 5.6 || p.Filaments[1].Material != "PETG" {
		t.Errorf("slot2 = %+v", p.Filaments[1])
	}
}

func TestParseGCode_BambuStudio(t *testing.T) {
	a := analyzeFixture(t, "bambustudio.gcode")

	if a.Slicer.Name != "BambuStudio" {
		t.Errorf("slicer name = %q", a.Slicer.Name)
	}
	if a.Slicer.Version != "01.08.00.00" {
		t.Errorf("slicer version = %q", a.Slicer.Version)
	}
	p := a.Plates[0]
	if p.PrintTimeSeconds != 2*3600+15*60+10 {
		t.Errorf("print time = %d", p.PrintTimeSeconds)
	}
	// The second slot is 0g and must be dropped.
	if len(p.Filaments) != 1 {
		t.Fatalf("filaments = %d, want 1 (0g dropped)", len(p.Filaments))
	}
	if p.Filaments[0].Grams != 25.5 || p.Filaments[0].Slot != 1 {
		t.Errorf("slot1 = %+v", p.Filaments[0])
	}
}

func TestParseGCode_Cura(t *testing.T) {
	a := analyzeFixture(t, "cura.gcode")

	if a.Slicer.Name != "Cura" {
		t.Errorf("slicer name = %q", a.Slicer.Name)
	}
	if a.Slicer.Version != "5.6.0" {
		t.Errorf("slicer version = %q", a.Slicer.Version)
	}
	p := a.Plates[0]
	if p.PrintTimeSeconds != 3600 {
		t.Errorf("print time = %d", p.PrintTimeSeconds)
	}
	if !p.Estimated {
		t.Errorf("expected estimated=true for Cura (grams from length)")
	}
	if len(p.Filaments) != 1 {
		t.Fatalf("filaments = %d", len(p.Filaments))
	}
	// 3.21 m of 1.75mm PLA ~= 9.57 g.
	if g := p.Filaments[0].Grams; g < 9.4 || g > 9.7 {
		t.Errorf("estimated grams = %v, want ~9.57", g)
	}
	if p.Filaments[0].LengthMM == nil || *p.Filaments[0].LengthMM != 3210 {
		t.Errorf("length = %v", p.Filaments[0].LengthMM)
	}
}

// TestParseGCode_TailScan ensures metadata placed AFTER the 2MB head window (near
// the end of the file) is still found via the tail pass.
func TestParseGCode_TailScan(t *testing.T) {
	var buf bytes.Buffer
	buf.WriteString("; generated by PrusaSlicer 2.7.1 on test\n")
	// ~3MB of non-metadata moves to push the footer past the head window.
	line := "G1 X100 Y100 E1.5 F1200\n"
	for buf.Len() < 3<<20 {
		buf.WriteString(line)
	}
	buf.WriteString("; filament used [g] = 42.00\n")
	buf.WriteString("; estimated printing time (normal mode) = 3h 0m 0s\n")

	data := buf.Bytes()
	a, err := ParseGCode(bytes.NewReader(data), int64(len(data)))
	if err != nil {
		t.Fatalf("ParseGCode: %v", err)
	}
	p := a.Plates[0]
	if p.PrintTimeSeconds != 3*3600 {
		t.Errorf("print time = %d, tail metadata not found", p.PrintTimeSeconds)
	}
	if len(p.Filaments) != 1 || p.Filaments[0].Grams != 42.0 {
		t.Errorf("filaments = %+v, tail metadata not found", p.Filaments)
	}
}
