package parser

import (
	"bytes"
	"errors"
	"strings"
	"testing"

	"github.com/RodolfoBonis/spooliq/features/slicer/domain/entities"
)

func TestSanitizeAnalysis_CapsAndValidation(t *testing.T) {
	a := &entities.Analysis{
		Slicer: entities.Slicer{
			Name:    strings.Repeat("N", 200),
			Version: strings.Repeat("v", 200),
		},
		Warnings: make([]string, 40),
	}
	// 100 plates (cap 64); first plate overloaded with filaments and junk strings.
	for i := 0; i < 100; i++ {
		p := entities.Plate{Index: i + 1, Name: strings.Repeat("P", 300)}
		if i == 0 {
			for j := 0; j < 50; j++ { // cap 32
				p.Filaments = append(p.Filaments, entities.Filament{
					Slot:     j + 1,
					Grams:    1,
					ColorHex: "#FF0000",
					Material: strings.Repeat("M", 100),
				})
			}
		}
		a.Plates = append(a.Plates, p)
	}

	sanitizeAnalysis(a)

	if len(a.Plates) != maxPlates {
		t.Errorf("plates = %d, want %d", len(a.Plates), maxPlates)
	}
	if len(a.Plates[0].Filaments) != maxFilamentsPerPlate {
		t.Errorf("filaments = %d, want %d", len(a.Plates[0].Filaments), maxFilamentsPerPlate)
	}
	if len([]rune(a.Slicer.Name)) != maxSlicerFieldLen || len([]rune(a.Slicer.Version)) != maxSlicerFieldLen {
		t.Errorf("slicer fields not capped: name=%d version=%d", len([]rune(a.Slicer.Name)), len([]rune(a.Slicer.Version)))
	}
	if len([]rune(a.Plates[0].Name)) != maxPlateNameLen {
		t.Errorf("plate name = %d, want %d", len([]rune(a.Plates[0].Name)), maxPlateNameLen)
	}
	if len([]rune(a.Plates[0].Filaments[0].Material)) != maxMaterialLen {
		t.Errorf("material = %d, want %d", len([]rune(a.Plates[0].Filaments[0].Material)), maxMaterialLen)
	}
	if len(a.Warnings) != maxWarnings {
		t.Errorf("warnings = %d, want %d", len(a.Warnings), maxWarnings)
	}
}

func TestSanitizeAnalysis_ColorNormalizationAndDrop(t *testing.T) {
	a := &entities.Analysis{
		Plates: []entities.Plate{{
			Index: 1,
			Filaments: []entities.Filament{
				{Slot: 1, Grams: 1, ColorHex: "#00ae42ff"},   // RGBA -> #00AE42
				{Slot: 2, Grams: 1, ColorHex: "not-a-color"}, // invalid -> dropped
			},
		}},
	}
	sanitizeAnalysis(a)
	if got := a.Plates[0].Filaments[0].ColorHex; got != "#00AE42" {
		t.Errorf("color[0] = %q, want #00AE42", got)
	}
	if got := a.Plates[0].Filaments[1].ColorHex; got != "" {
		t.Errorf("invalid color should be dropped, got %q", got)
	}
}

func TestParseGCode_RGBAColorNormalized(t *testing.T) {
	src := "; generated by BambuStudio 01.08.00.00\n" +
		"; total estimated time: 30m\n" +
		"; filament used [g] = 10.00\n" +
		"; filament_colour = #00AE42FF\n" +
		"; filament_type = PLA\n"
	a, err := ParseGCode(bytes.NewReader([]byte(src)), int64(len(src)))
	if err != nil {
		t.Fatalf("ParseGCode: %v", err)
	}
	if got := a.Plates[0].Filaments[0].ColorHex; got != "#00AE42" {
		t.Errorf("color = %q, want #00AE42 (alpha dropped, uppercased)", got)
	}
}

func TestParseGCode_EmptyIsNotSliced(t *testing.T) {
	cases := map[string]string{
		"completely empty": "",
		"only moves":       "G1 X1 Y1\nG1 X2 Y2\n",
		"comments no data": "; generated by PrusaSlicer 2.7.1\n; some note\n",
	}
	for name, src := range cases {
		t.Run(name, func(t *testing.T) {
			_, err := ParseGCode(bytes.NewReader([]byte(src)), int64(len(src)))
			if !errors.Is(err, ErrNotSliced) {
				t.Fatalf("err = %v, want ErrNotSliced", err)
			}
		})
	}
}

func TestParseGCode_TimeOnlyIsSliced(t *testing.T) {
	// Time present but no filament usage still counts as sliced.
	src := "; estimated printing time (normal mode) = 10m\n"
	a, err := ParseGCode(bytes.NewReader([]byte(src)), int64(len(src)))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if a.Plates[0].PrintTimeSeconds != 600 {
		t.Errorf("print time = %d", a.Plates[0].PrintTimeSeconds)
	}
}
