package parser

import (
	"archive/zip"
	"bytes"
	"errors"
	"testing"

	"github.com/RodolfoBonis/spooliq/features/slicer/domain/entities"
)

// buildZip assembles an in-memory zip from name->content entries (Deflate).
func buildZip(t *testing.T, entries map[string]string) []byte {
	t.Helper()
	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)
	for name, content := range entries {
		w, err := zw.Create(name)
		if err != nil {
			t.Fatalf("zip create %s: %v", name, err)
		}
		if _, err := w.Write([]byte(content)); err != nil {
			t.Fatalf("zip write %s: %v", name, err)
		}
	}
	if err := zw.Close(); err != nil {
		t.Fatalf("zip close: %v", err)
	}
	return buf.Bytes()
}

const bambuSliceInfo = `<?xml version="1.0" encoding="UTF-8"?>
<!-- generated by BambuStudio -->
<config>
  <plate>
    <metadata key="index" value="1"/>
    <metadata key="prediction" value="3600"/>
    <metadata key="weight" value="17.94"/>
    <filament id="1" type="PLA" color="#FF0000" used_m="4.10" used_g="12.34"/>
    <filament id="2" type="PETG" color="#00FF00" used_m="1.80" used_g="5.60"/>
  </plate>
  <plate>
    <metadata key="index" value="2"/>
    <metadata key="prediction" value="1800"/>
    <metadata key="weight" value="8.00"/>
    <filament id="1" type="PLA" color="#0000FF" used_m="2.00" used_g="8.00"/>
  </plate>
</config>`

func TestParse3MF_BambuSliced(t *testing.T) {
	data := buildZip(t, map[string]string{
		"3D/3dmodel.model":              "<model/>",
		"Metadata/slice_info.config":    bambuSliceInfo,
		"Metadata/project_settings.cfg": "{}",
	})

	a, err := Parse3MF(bytes.NewReader(data), int64(len(data)))
	if err != nil {
		t.Fatalf("Parse3MF: %v", err)
	}
	if a.Source != entities.Source3MF {
		t.Errorf("source = %q", a.Source)
	}
	if a.Slicer.Name != "BambuStudio" {
		t.Errorf("slicer = %q", a.Slicer.Name)
	}
	if len(a.Plates) != 2 {
		t.Fatalf("plates = %d", len(a.Plates))
	}

	p1 := a.Plates[0]
	if p1.Index != 1 || p1.PrintTimeSeconds != 3600 || p1.Estimated {
		t.Errorf("plate1 = %+v", p1)
	}
	if len(p1.Filaments) != 2 {
		t.Fatalf("plate1 filaments = %d", len(p1.Filaments))
	}
	if p1.Filaments[0].Grams != 12.34 || p1.Filaments[0].ColorHex != "#FF0000" || p1.Filaments[0].Material != "PLA" {
		t.Errorf("p1 slot1 = %+v", p1.Filaments[0])
	}
	if p1.Filaments[0].LengthMM == nil || *p1.Filaments[0].LengthMM != 4100 {
		t.Errorf("p1 slot1 length = %v", p1.Filaments[0].LengthMM)
	}
	if p1.Filaments[1].Grams != 5.6 || p1.Filaments[1].Material != "PETG" {
		t.Errorf("p1 slot2 = %+v", p1.Filaments[1])
	}

	p2 := a.Plates[1]
	if p2.Index != 2 || p2.PrintTimeSeconds != 1800 {
		t.Errorf("plate2 = %+v", p2)
	}
	if len(p2.Filaments) != 1 || p2.Filaments[0].Grams != 8.0 || p2.Filaments[0].ColorHex != "#0000FF" {
		t.Errorf("plate2 filaments = %+v", p2.Filaments)
	}
}

func TestParse3MF_ProjectSettingsColorFallback(t *testing.T) {
	// slice_info filaments without color/type; project_settings.config supplies them.
	sliceInfo := `<?xml version="1.0"?>
<config>
  <plate>
    <metadata key="index" value="1"/>
    <metadata key="prediction" value="600"/>
    <filament id="1" used_g="3.00"/>
    <filament id="2" used_g="4.00"/>
  </plate>
</config>`
	settings := `{"filament_colour":["#AABBCC","#DDEEFF"],"filament_type":["PLA","PETG"]}`

	data := buildZip(t, map[string]string{
		"Metadata/slice_info.config":       sliceInfo,
		"Metadata/project_settings.config": settings,
	})
	a, err := Parse3MF(bytes.NewReader(data), int64(len(data)))
	if err != nil {
		t.Fatalf("Parse3MF: %v", err)
	}
	fs := a.Plates[0].Filaments
	if len(fs) != 2 {
		t.Fatalf("filaments = %d", len(fs))
	}
	if fs[0].ColorHex != "#AABBCC" || fs[0].Material != "PLA" {
		t.Errorf("slot1 fallback = %+v", fs[0])
	}
	if fs[1].ColorHex != "#DDEEFF" || fs[1].Material != "PETG" {
		t.Errorf("slot2 fallback = %+v", fs[1])
	}
}

func TestParse3MF_EmbeddedGCodeFallback(t *testing.T) {
	// No slice_info: a plate_1.gcode is parsed with the G-code parser.
	plateGcode := "; generated by OrcaSlicer 2.0.0\n; total estimated time: 30m\n; filament used [g] = 7.70\n; filament_colour = #123456\n; filament_type = PLA\n"
	data := buildZip(t, map[string]string{
		"3D/3dmodel.model":       "<model/>",
		"Metadata/plate_1.gcode": plateGcode,
	})
	a, err := Parse3MF(bytes.NewReader(data), int64(len(data)))
	if err != nil {
		t.Fatalf("Parse3MF: %v", err)
	}
	if a.Source != entities.Source3MF {
		t.Errorf("source = %q", a.Source)
	}
	if len(a.Plates) != 1 {
		t.Fatalf("plates = %d", len(a.Plates))
	}
	p := a.Plates[0]
	if p.Index != 1 || p.PrintTimeSeconds != 30*60 {
		t.Errorf("plate = %+v", p)
	}
	if len(p.Filaments) != 1 || p.Filaments[0].Grams != 7.7 {
		t.Errorf("filaments = %+v", p.Filaments)
	}
}

func TestParse3MF_Unsliced(t *testing.T) {
	// A design-only PrusaSlicer-style 3MF: model geometry but no slicing data.
	data := buildZip(t, map[string]string{
		"[Content_Types].xml":       "<Types/>",
		"3D/3dmodel.model":          "<model><resources/></model>",
		"Metadata/Slic3r_PE.config": "; no slicing here",
	})
	_, err := Parse3MF(bytes.NewReader(data), int64(len(data)))
	if !errors.Is(err, ErrNotSliced) {
		t.Fatalf("err = %v, want ErrNotSliced", err)
	}
}

func TestParse3MF_CorruptZip(t *testing.T) {
	_, err := Parse3MF(bytes.NewReader([]byte("not a zip at all")), 16)
	if !errors.Is(err, ErrCorruptFile) {
		t.Fatalf("err = %v, want ErrCorruptFile", err)
	}
}

func TestParse3MF_ZipBombGuard(t *testing.T) {
	// A highly compressible entry (2MB of zeros) trips the compression-ratio guard.
	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)
	w, err := zw.Create("Metadata/slice_info.config")
	if err != nil {
		t.Fatalf("create: %v", err)
	}
	zeros := make([]byte, 2<<20) // 2MB of 0x00 -> compresses to a few KB
	if _, err := w.Write(zeros); err != nil {
		t.Fatalf("write: %v", err)
	}
	if err := zw.Close(); err != nil {
		t.Fatalf("close: %v", err)
	}
	data := buf.Bytes()

	_, perr := Parse3MF(bytes.NewReader(data), int64(len(data)))
	if !errors.Is(perr, ErrCorruptFile) {
		t.Fatalf("err = %v, want ErrCorruptFile (zip bomb)", perr)
	}
}
