package usecases

import (
	"archive/zip"
	"bytes"
	"context"
	"encoding/json"
	"mime/multipart"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/RodolfoBonis/go-otel-agent/logger"
	"github.com/RodolfoBonis/spooliq/features/slicer/domain/service"
	"github.com/RodolfoBonis/spooliq/features/slicer/domain/suggest"
	"github.com/gin-gonic/gin"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func init() { gin.SetMode(gin.TestMode) }

// noopCatalog yields no filaments, so suggestions resolve to nil.
type noopCatalog struct{}

func (noopCatalog) LoadCandidates(_ context.Context, _ string) ([]suggest.Candidate, error) {
	return nil, nil
}

func newUC() *SlicerUseCase {
	svc := service.NewService(noopCatalog{}, &logger.NoopLogger{})
	return &SlicerUseCase{service: svc, logger: &logger.NoopLogger{}}
}

func ctxWithOrg(org string) (*gin.Context, *httptest.ResponseRecorder) {
	rec := httptest.NewRecorder()
	c, _ := gin.CreateTestContext(rec)
	if org != "" {
		c.Set("organization_id", org)
	}
	c.Set("user_id", "user-1")
	return c, rec
}

func multipartReqBytes(t *testing.T, filename string, content []byte) *http.Request {
	t.Helper()
	var buf bytes.Buffer
	w := multipart.NewWriter(&buf)
	if filename != "" {
		fw, err := w.CreateFormFile("file", filename)
		require.NoError(t, err)
		_, _ = fw.Write(content)
	}
	_ = w.Close()
	req := httptest.NewRequest(http.MethodPost, "/slicer/analyze", &buf)
	req.Header.Set("Content-Type", w.FormDataContentType())
	return req
}

func multipartReq(t *testing.T, filename, content string) *http.Request {
	return multipartReqBytes(t, filename, []byte(content))
}

func decode(t *testing.T, rec *httptest.ResponseRecorder) map[string]any {
	t.Helper()
	var body map[string]any
	require.NoError(t, json.Unmarshal(rec.Body.Bytes(), &body))
	return body
}

func zipBytes(t *testing.T, entries map[string]string) []byte {
	t.Helper()
	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)
	for name, content := range entries {
		w, err := zw.Create(name)
		require.NoError(t, err)
		_, err = w.Write([]byte(content))
		require.NoError(t, err)
	}
	require.NoError(t, zw.Close())
	return buf.Bytes()
}

const prusaGCode = "; generated by PrusaSlicer 2.7.1 on test\n" +
	"; estimated printing time (normal mode) = 1h 0m 0s\n" +
	"; filament used [g] = 10.00, 5.00\n" +
	"; filament_colour = #FF0000;#00FF00\n" +
	"; filament_type = PLA;PETG\n"

func TestAnalyze_OrganizationRequired(t *testing.T) {
	uc := newUC()
	c, rec := ctxWithOrg("")
	c.Request = multipartReq(t, "a.gcode", prusaGCode)
	uc.Analyze(c)
	assert.Equal(t, http.StatusBadRequest, rec.Code)
	assert.Equal(t, "organization_required", decode(t, rec)["code"])
}

func TestAnalyze_FileRequired(t *testing.T) {
	uc := newUC()
	c, rec := ctxWithOrg("org-1")
	c.Request = multipartReq(t, "", "")
	uc.Analyze(c)
	assert.Equal(t, http.StatusBadRequest, rec.Code)
	assert.Equal(t, "file_required", decode(t, rec)["code"])
}

func TestAnalyze_UnsupportedFormat(t *testing.T) {
	uc := newUC()
	c, rec := ctxWithOrg("org-1")
	c.Request = multipartReq(t, "model.stl", "solid x")
	uc.Analyze(c)
	assert.Equal(t, http.StatusBadRequest, rec.Code)
	assert.Equal(t, "unsupported_file_format", decode(t, rec)["code"])
}

func TestAnalyze_Success(t *testing.T) {
	uc := newUC()
	c, rec := ctxWithOrg("org-1")
	c.Request = multipartReq(t, "part.gcode", prusaGCode)
	uc.Analyze(c)
	require.Equal(t, http.StatusOK, rec.Code)

	body := decode(t, rec)
	assert.Equal(t, "gcode", body["source"])
	plates, ok := body["plates"].([]any)
	require.True(t, ok)
	require.Len(t, plates, 1)
	plate := plates[0].(map[string]any)
	assert.EqualValues(t, 3600, plate["print_time_seconds"])
	fils := plate["filaments"].([]any)
	require.Len(t, fils, 2)
	// With an empty catalog, suggestion must be present and null.
	f0 := fils[0].(map[string]any)
	assert.Contains(t, f0, "suggestion")
	assert.Nil(t, f0["suggestion"])
}

func TestAnalyze_NotSliced(t *testing.T) {
	uc := newUC()
	c, rec := ctxWithOrg("org-1")
	data := zipBytes(t, map[string]string{"3D/3dmodel.model": "<model/>"})
	c.Request = multipartReqBytes(t, "design.3mf", data)
	uc.Analyze(c)
	assert.Equal(t, http.StatusUnprocessableEntity, rec.Code)
	assert.Equal(t, "file_not_sliced", decode(t, rec)["code"])
}

func TestAnalyze_InvalidFile(t *testing.T) {
	uc := newUC()
	c, rec := ctxWithOrg("org-1")
	c.Request = multipartReqBytes(t, "broken.3mf", []byte("this is not a zip"))
	uc.Analyze(c)
	assert.Equal(t, http.StatusBadRequest, rec.Code)
	assert.Equal(t, "invalid_file", decode(t, rec)["code"])
}

func TestAnalyze_FileTooLarge(t *testing.T) {
	old := uploadBodyLimit
	uploadBodyLimit = 32 // tiny cap to force the 413 path
	defer func() { uploadBodyLimit = old }()

	uc := newUC()
	c, rec := ctxWithOrg("org-1")
	c.Request = multipartReq(t, "big.gcode", prusaGCode+prusaGCode)
	uc.Analyze(c)
	assert.Equal(t, http.StatusRequestEntityTooLarge, rec.Code)
	assert.Equal(t, "file_too_large", decode(t, rec)["code"])
}
